// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/articles/[id]/status.tsx";
import * as $1 from "./routes/articles/index.tsx";
import * as $2 from "./routes/blog/[id]/status.tsx";
import * as $3 from "./routes/blog/index.tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/BasicFooter.tsx";
import * as $$1 from "./islands/BasicHead.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Meta.tsx";

const manifest = {
  routes: {
    "./routes/articles/[id]/status.tsx": $0,
    "./routes/articles/index.tsx": $1,
    "./routes/blog/[id]/status.tsx": $2,
    "./routes/blog/index.tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/BasicFooter.tsx": $$0,
    "./islands/BasicHead.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Meta.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
