// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/blogs/[id]/edit.tsx";
import * as $1 from "./routes/blogs/[id]/status.tsx";
import * as $2 from "./routes/blogs/index.tsx";
import * as $3 from "./routes/blogs/manage.tsx";
import * as $4 from "./routes/blogs/new.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/sessions/new.tsx";
import * as $$0 from "./islands/BasicFooter.tsx";
import * as $$1 from "./islands/BasicHead.tsx";
import * as $$2 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/blogs/[id]/edit.tsx": $0,
    "./routes/blogs/[id]/status.tsx": $1,
    "./routes/blogs/index.tsx": $2,
    "./routes/blogs/manage.tsx": $3,
    "./routes/blogs/new.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/sessions/new.tsx": $6,
  },
  islands: {
    "./islands/BasicFooter.tsx": $$0,
    "./islands/BasicHead.tsx": $$1,
    "./islands/Counter.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
